# Generated by Django 4.1.3 on 2022-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortnaiteblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='images',
            new_name='images1',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='images2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='images3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='images4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='images5',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
