# Generated by Django 4.1.3 on 2022-11-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortnaiteblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='titleImages',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
