# Generated by Django 4.1.3 on 2022-11-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortnaiteblog', '0002_rename_images_blogmodel_images1_blogmodel_images2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.FileField(upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='images4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='images5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
