# Generated by Django 4.1.3 on 2022-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortnaiteblog', '0002_alter_blogmodel_titleimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='endContents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
