# Generated by Django 4.1.3 on 2022-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortnaiteblog', '0003_blogmodel_endcontents'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='articleContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
