# Generated by Django 4.1.3 on 2022-11-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortnaiteblog', '0003_alter_blogmodel_content_alter_blogmodel_images2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.TextField(),
        ),
    ]
