# Generated by Django 4.1.3 on 2022-11-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortnaiteblog', '0004_alter_blogmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.FileField(upload_to='', verbose_name='添付ファイル'),
        ),
    ]
